/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/AboutSection.vue')['default']
    Authorization: typeof import('./components/Authorization.vue')['default']
    Bot: typeof import('./components/Bot.vue')['default']
    CheckerBlocks: typeof import('./components/CheckerBlocks.vue')['default']
    DocumentTemplates: typeof import('./components/DocumentTemplates.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    JudicialPractice: typeof import('./components/JudicialPractice.vue')['default']
    LinksBlock: typeof import('./components/LinksBlock.vue')['default']
    PracticeBlocks: typeof import('./components/PracticeBlocks.vue')['default']
    RecommendationCard: typeof import('./components/RecommendationCard.vue')['default']
    RecommendationSection: typeof import('./components/RecommendationSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDocumentBlock: typeof import('./components/SearchDocumentBlock.vue')['default']
    SearchInput: typeof import('./components/SearchInput.vue')['default']
    TextArticle: typeof import('./components/TextArticle.vue')['default']
  }
}
