/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AboutPage': RouteRecordInfo<'/AboutPage', '/AboutPage', Record<never, never>, Record<never, never>>,
    '/Checklist': RouteRecordInfo<'/Checklist', '/Checklist', Record<never, never>, Record<never, never>>,
    '/EnterPage': RouteRecordInfo<'/EnterPage', '/EnterPage', Record<never, never>, Record<never, never>>,
    '/JudicialReview': RouteRecordInfo<'/JudicialReview', '/JudicialReview', Record<never, never>, Record<never, never>>,
    '/SearchPage': RouteRecordInfo<'/SearchPage', '/SearchPage', Record<never, never>, Record<never, never>>,
    '/TextPage': RouteRecordInfo<'/TextPage', '/TextPage', Record<never, never>, Record<never, never>>,
    '/VerificationPage': RouteRecordInfo<'/VerificationPage', '/VerificationPage', Record<never, never>, Record<never, never>>,
  }
}
